import { DEMO_COMPANY_NAME, MANUFACTURER_COMPANY_NAME } from '@/constants/loginAccounts'
import { PLATFORM_COMPANY_CODE, PLATFORM_COMPANY_NAME } from '@/constants/platformCompany'

/** 与登录页三个测试账号对应，默认写入平台客户列表 */
export const TENANT_PLATFORM_CUSTOMER_SEED = [
  {
    id: 101,
    platformStatus: 'platformAudited',
    companyCode: PLATFORM_COMPANY_CODE,
    companyName: PLATFORM_COMPANY_NAME,
    companyShortName: '医享医疗',
    companyType: 'platform',
    companyCategory: '平',
    pinyin: 'hangzhouyixiang',
    contact: '平台BOSS',
    phone: '0571-88888888',
    email: '',
    province: '浙江省',
    city: '杭州市',
    address: '浙江省杭州市滨江区某某路168号',
    companyIntro: '平台运营主体',
    businessScope: '',
    legalPerson: '',
    registerCapital: '',
    establishDate: '',
    license: '91330100MA2CXXXXXX',
    licenseExpire: '',
    taxId: '91330100MA2CXXXXXX',
    bank: '',
    bankAccount: '',
    documents: [],
    platformUser: 'admin',
    createDate: '2024-01-01',
    creator: '系统',
    editor: '系统',
    editDate: '2024-01-01',
    remark: '登录测试账号：admin / admin123',
    status: 'normal',
    recordStatus: '是',
    recordDate: '2024-01-01'
  },
  {
    id: 102,
    platformStatus: 'platformAudited',
    companyCode: 'DEMO',
    companyName: DEMO_COMPANY_NAME,
    companyShortName: '经营公司',
    companyType: 'distributor',
    companyCategory: '销',
    pinyin: 'ylqxsjygs',
    contact: '演示管理员',
    phone: '025-88888888',
    email: '',
    province: '江苏省',
    city: '南京市',
    address: '江苏省南京市鼓楼区中山北路100号',
    companyIntro: '',
    businessScope: '',
    legalPerson: '',
    registerCapital: '',
    establishDate: '',
    license: '91320000MA1FL6XQ8R',
    licenseExpire: '',
    taxId: '91320000MA1FL6XQ8R',
    bank: '',
    bankAccount: '',
    documents: [],
    platformUser: 'demo',
    createDate: '2024-01-01',
    creator: '系统',
    editor: '系统',
    editDate: '2024-01-01',
    remark: '登录测试账号：demo / demo123',
    status: 'normal',
    recordStatus: '是',
    recordDate: '2024-01-01'
  },
  {
    id: 103,
    platformStatus: 'platformAudited',
    companyCode: 'MFG',
    companyName: MANUFACTURER_COMPANY_NAME,
    companyShortName: '生产企业',
    companyType: 'manufacturer',
    companyCategory: '产',
    pinyin: 'ylqxscyxgs',
    contact: '生产厂家管理员',
    phone: '0574-66668888',
    email: '',
    province: '浙江省',
    city: '宁波市',
    address: '浙江省宁波市鄞州区创新大道88号',
    companyIntro: '',
    businessScope: '',
    legalPerson: '',
    registerCapital: '',
    establishDate: '',
    license: '91330200MA2HXXXXXX',
    licenseExpire: '',
    taxId: '91330200MA2HXXXXXX',
    bank: '',
    bankAccount: '',
    documents: [],
    platformUser: 'factory',
    createDate: '2024-01-01',
    creator: '系统',
    editor: '系统',
    editDate: '2024-01-01',
    remark: '登录测试账号：factory / factory123',
    status: 'normal',
    recordStatus: '是',
    recordDate: '2024-01-01'
  }
]

export const TENANT_PLATFORM_CUSTOMER_CODES = TENANT_PLATFORM_CUSTOMER_SEED.map(item => item.companyCode)
